### ISSUE TITLE
v3.0.1 build failure due to the test test_blank_choices failing

### ISSUE THREAD

**Issue by stianlagstad** [coleifer/wtf-peewee#54]
From the [recent build logs](https://travis-ci.org/github/coleifer/wtf-peewee/jobs/713454318) I see this test failure:
```
======================================================================
ERROR: test_blank_choices (wtfpeewee.tests.WTFPeeweeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/coleifer/wtf-peewee/wtfpeewee/tests.py", line 231, in test_blank_choices
    self.assertTrue(form.validate())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/wtforms/fields/core.py", line 215, in validate
    self.pre_validate(form)
  File "/home/travis/build/coleifer/wtf-peewee/wtfpeewee/fields.py", line 187, in pre_validate
    super(SelectChoicesField, self).pre_validate(form)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/wtforms/fields/core.py", line 509, in pre_validate
    for _, _, match in self.iter_choices():
  File "/home/travis/build/coleifer/wtf-peewee/wtfpeewee/fields.py", line 163, in iter_choices
    yield (value, label, self.coerce(value) == self.data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I bumped into this myself because I tried to install [buku](https://github.com/jarun/buku) in NixOS, and the wtf-peewee module (being a dependency of buku) in NixOS was [just upgraded from 3.0.0 to 3.0.1](https://github.com/NixOS/nixpkgs/commit/30a5ce48e59d045fd75c14a16b833c33e7cff122) leading to the build failing.

I'm making this issue to let you know about the build failure in case you missed it. I'll look into the test failure myself, but perhaps not tonight :)

**Comment by coleifer** [comment]
I've been running wtforms 2.1 locally, but it looks like something has changed between 2.1 and 2.3.3 (which also caused the travis-ci build to fail). I will look into this, thanks for reporting!

**Comment by coleifer** [comment]
fdab8c36971f7ed9b6e82cbef5a95dbfcc5a70e1

**Comment by stianlagstad** [comment]
Thank you very much! :)

**Comment by stianlagstad** [comment]
I do realize this was just a failing test, but could you release version 3.0.2?

**Comment by stianlagstad** [comment]
I do realize that this was just a test failure, but could you release version 3.0.2 of wtf-peewee?

**Comment by coleifer** [comment]
Done

**Comment by stianlagstad** [comment]
Thank you @coleifer ! Can I buy you a coffee through https://www.buymeacoffee.com/ or similar as a thank you?

**Comment by coleifer** [comment]
No problem at all, bro. I appreciate the offer but the thanks is more than enough.
