### ISSUE TITLE
compatibility issues with WTForms >= 3.0.0

### ISSUE THREAD

**Issue by mcepl** [coleifer/wtf-peewee#57]
When packaging wtf-peewee for openSUSE with WTForms 3.0.1 the test suite erros with this:
```
[   32s] ======================================================================
[   32s] ERROR: test_entry_form (wtfpeewee.tests.WTFPeeweeTestCase)
[   32s] ----------------------------------------------------------------------
[   32s] Traceback (most recent call last):
[   32s]   File "/home/abuild/rpmbuild/BUILD/wtf-peewee-3.0.3/wtfpeewee/tests.py", line 259, in test_entry_form
[   32s]     form = EntryForm()
[   32s]   File "/usr/lib/python3.9/site-packages/wtforms/form.py", line 208, in __call__
[   32s]     return type.__call__(cls, *args, **kwargs)
[   32s]   File "/usr/lib/python3.9/site-packages/wtforms/form.py", line 286, in __init__
[   32s]     self.process(formdata, obj, data=data, **kwargs)
[   32s]   File "/usr/lib/python3.9/site-packages/wtforms/form.py", line 127, in process
[   32s]     field.process(formdata, data, extra_filters=field_extra_filters)
[   32s] TypeError: process() got an unexpected keyword argument 'extra_filters'
```

For compatibility with the current WTForms I had to apply this patch:
```diff
---
 wtfpeewee/fields.py |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- a/wtfpeewee/fields.py
+++ b/wtfpeewee/fields.py
@@ -112,7 +112,7 @@ class WPDateTimeField(FormField):
         super(WPDateTimeField, self).__init__(
             DynamicForm, label, validators=None, **kwargs)

-    def process(self, formdata, data=_unset_value):
+    def process(self, formdata, data=_unset_value, extra_filters=None):
         prefix = self.name + self.separator
         kwargs = {}
         if data is _unset_value:
```

**Comment by coleifer** [comment]
This is fixed in master as of 3 months ago but I haven't tagged a release yet.

https://github.com/coleifer/wtf-peewee/commit/b1764f4474c73a9a2b34ae6b7db61274f5252a7f

**Comment by coleifer** [comment]
Release 3.0.4 which contais the above commit. Should be all set.
